### ISSUE TITLE
Incorrect commenting of scroll function

### ISSUE THREAD

**Issue by Philip-Wang01** [jieliu2000/RPALite#1]
![image](https://github.com/user-attachments/assets/909fa0f4-c124-46d5-8b5c-03d746e92a2a)

**Comment by jieliu2000** [comment]
@Philip-Wang01 The comments of the scroll function has been fixed. Please check the latest version. Thanks.

**Comment by Philip-Wang01** [comment]
@jieliu2000 Verified this issue in latest version, there is still an issue in the description of positive and negative values. Positive value means scrolling up, and negative value means scrolling down. 
![image](https://github.com/user-attachments/assets/eee68446-8d9f-48d6-9725-5ce650c30e67)

**Comment by jieliu2000** [comment]
Hi @Philip-Wang01 ,

I updated the comments of scroll function in commit c86136e

**Comment by Philip-Wang01** [comment]
Verified this in the latest version and the issue has been fixed. 
![image](https://github.com/user-attachments/assets/f3a2900d-9871-486a-aa5c-beac9934bbc4)
